### ISSUE TITLE
Adding to Piles doesn't work properly when deck_count > 1.

### ISSUE THREAD

**Issue by MattimusRex** [crobertsbmw/deckofcards#35] opened 2017-02-24 15:17 UTC
If you create a deck with deck_count > 1, adding to a pile will return success but remaining will equal 0.  You are unable to draw from the pile as well.  I'm somewhat new to this, so I may be wrong, but after some testing and looking at the views.py I think the bug is in this line:
        cards = [x for x in cards.split(',') if x not in deck.stack and x in CARDS]

When it checks that the card isn't in the deck.stack, it is finding the other copies of the card and then not adding the card to the pile.  If you create a deck with deck_count 2 and repeatedly draw a single card and add it to a pile, the pile will return success but remain empty until you add the second copy of a card.  Since the first copy has already been drawn from the deck, it then correctly adds to the pile.

**Comment by crobertsbmw** [comment] 2017-02-25 00:39
Thanks for bringing this to my attention. I think there are two issues. The first issue issue is the line you suggested:
`cards = [x for x in cards.split(',') if x not in deck.stack and x in CARDS]`.
The second problem is with the next few lines after the one above. The problem is that if you have a 2Spades in `pile1` and `pile2` and then you try to add a 2S to `pile3`, then we don't know which 2S to move to `pile3`. I don't see an easy fix for this without adding some type of unique identifier to each card.
Currently in the database less than 1% of the decks are evening using piles, and only a fraction of those are going to be multiple decks. Unfortunately, I have to mark this as a wontfix, unless you want to try to tackle it and submit a pull request. I've made a note on the documentation page saying that it doesn't work with multiple decks.
Thanks.

**Closed** 2017-02-25 00:39 UTC
Labels: wontfix
